ProgramNode <1:1>
  FuncDefNode <1:5> main: int ()
    CompoundStmtNode <1:12>
      ExprStmtNode <2:3>
        BinaryExprNode <2:5> int +
          IntConstExprNode <2:3> 1: int
          IntConstExprNode <2:7> 2: int
      ExprStmtNode <3:3>
        BinaryExprNode <3:5> int -
          IntConstExprNode <3:3> 1: int
          IntConstExprNode <3:7> 2: int
      ExprStmtNode <4:3>
        BinaryExprNode <4:5> int *
          IntConstExprNode <4:3> 1: int
          IntConstExprNode <4:7> 2: int
      ExprStmtNode <5:3>
        BinaryExprNode <5:5> int /
          IntConstExprNode <5:3> 1: int
          IntConstExprNode <5:7> 2: int
      ExprStmtNode <6:3>
        BinaryExprNode <6:5> int %
          IntConstExprNode <6:3> 1: int
          IntConstExprNode <6:7> 2: int
      ExprStmtNode <7:3>
        BinaryExprNode <7:21> int +
          BinaryExprNode <7:13> int +
            BinaryExprNode <7:5> int -
              IntConstExprNode <7:3> 1: int
              BinaryExprNode <7:9> int *
                IntConstExprNode <7:7> 2: int
                IntConstExprNode <7:11> 3: int
            BinaryExprNode <7:17> int /
              IntConstExprNode <7:15> 4: int
              IntConstExprNode <7:19> 5: int
          BinaryExprNode <7:25> int %
            IntConstExprNode <7:23> 6: int
            IntConstExprNode <7:27> 2: int
      ExprStmtNode <8:3>
        BinaryExprNode <8:5> int &
          IntConstExprNode <8:3> 1: int
          IntConstExprNode <8:7> 4: int
      ExprStmtNode <9:3>
        BinaryExprNode <9:5> int |
          IntConstExprNode <9:3> 1: int
          IntConstExprNode <9:7> 2: int
      ExprStmtNode <10:3>
        BinaryExprNode <10:5> int ^
          IntConstExprNode <10:3> 1: int
          IntConstExprNode <10:7> 3: int
      ExprStmtNode <11:3>
        BinaryExprNode <11:5> int <<
          IntConstExprNode <11:3> 1: int
          IntConstExprNode <11:8> 16: int
      ExprStmtNode <12:3>
        BinaryExprNode <12:9> int >>
          IntConstExprNode <12:3> 65536: int
          IntConstExprNode <12:12> 16: int
