TransUnitNode <1:1>
  ExternDeclNode <1:1>
    FuncDefNode <1:5> main: int ()
      CompoundStmtNode <1:12>
        DeclStmtNode <2:3>
          VarDeclNode <2:7> a: int
            IntConstExprNode <2:11> 0: int
        WhileStmtNode <3:3>
          // Do
          CompoundStmtNode <3:6>
            IfStmtNode <4:5>
              IntConstExprNode <4:9> 1: int
              // Then
              CompoundStmtNode <4:12>
                ExprStmtNode <5:7>
                  SimpleAssignmentExprNode <5:9> int
                    IdExprNode <5:7> a: int
                    IntConstExprNode <5:11> 5: int
                ContinueStmtNode <6:7>
            ExprStmtNode <8:5>
              SimpleAssignmentExprNode <8:7> int
                IdExprNode <8:5> a: int
                IntConstExprNode <8:9> 0: int
          // While
          BinaryExprNode <10:14> int <
            IdExprNode <10:12> a: int
            IntConstExprNode <10:16> 5: int
        ReturnStmtNode <12:3>
          IntConstExprNode <12:10> 0: int
