TransUnitNode <1:1>
  ExternDeclNode <1:1>
    FuncDefNode <1:5> main: int ()
      CompoundStmtNode <1:12>
        DeclStmtNode <2:3>
          VarDeclNode <2:7> i: int
            IntConstExprNode <2:11> 0: int
        DeclStmtNode <3:3>
          VarDeclNode <3:7> j: int
        DeclStmtNode <4:3>
          VarDeclNode <4:3> : int
        DeclStmtNode <5:3>
          VarDeclNode <5:7> a: int
          VarDeclNode <5:10> b: int
            IntConstExprNode <5:14> 1: int
          VarDeclNode <5:17> c: int
          VarDeclNode <5:20> d: int
            IntConstExprNode <5:24> 0: int
