ProgramNode <1:1>
  FuncDefNode <1:5> main: int
    CompoundStmtNode <1:12>
      DeclNode <2:7> i: int
        IntConstExprNode <2:11> 0: int
      WhileStmtNode <3:3>
        // Do
        CompoundStmtNode <3:6>
          ExprStmtNode <4:5>
            SimpleAssignmentExprNode <4:7> int
              IdExprNode <4:5> i: int
              BinaryExprNode <4:11> int +
                IdExprNode <4:9> i: int
                IntConstExprNode <4:13> 1: int
        // While
        BinaryExprNode <5:14> int <
          IdExprNode <5:12> i: int
          IntConstExprNode <5:16> 5: int
      ReturnStmtNode <7:3>
        IntConstExprNode <7:10> 0: int
