TransUnitNode <1:1>
  ExternDeclNode <1:1>
    DeclStmtNode <1:1>
      EnumDeclNode <1:5> (unnamed)
        EnumConstDeclNode <2:3> FALSE: int
        EnumConstDeclNode <3:3> TRUE: int
  ExternDeclNode <6:1>
    FuncDefNode <6:5> main: int ()
      CompoundStmtNode <6:12>
        DeclStmtNode <7:3>
          VarDeclNode <7:7> f: int
            IdExprNode <7:11> TRUE: enum (unnamed)
              IntConstExprNode <7:11> 1: int
        DeclStmtNode <9:3>
          EnumDeclNode <9:8> Color
            EnumConstDeclNode <10:5> RED: int
            EnumConstDeclNode <11:5> GREEN: int
              IntConstExprNode <11:13> 2: int
            EnumConstDeclNode <12:5> BLUE: int
        DeclStmtNode <16:3>
          VarDeclNode <16:7> r: int
            IdExprNode <16:11> RED: enum Color
              IntConstExprNode <16:11> 0: int
        DeclStmtNode <17:3>
          VarDeclNode <17:14> b: enum Color
            IdExprNode <17:18> GREEN: enum Color
              IntConstExprNode <17:18> 2: int
        DeclStmtNode <18:3>
          VarDeclNode <18:7> c: int
            IdExprNode <18:11> b: enum Color
        DeclStmtNode <22:3>
          EnumDeclNode <22:7> (unnamed)
            EnumConstDeclNode <23:5> MONDAY: int
              IntConstExprNode <23:14> 1: int
            EnumConstDeclNode <24:5> TUESDAY: int
            EnumConstDeclNode <25:5> WEDNESDAY: int
            EnumConstDeclNode <26:5> THURSDAY: int
            EnumConstDeclNode <27:5> FRIDAY: int
              IntConstExprNode <27:14> 5: int
            EnumConstDeclNode <28:5> SATURDAY: int
            EnumConstDeclNode <29:5> SUNDAY: int
          VarDeclNode <30:5> w: enum (unnamed)
            IdExprNode <30:9> MONDAY: enum (unnamed)
              IntConstExprNode <30:9> 1: int
        DeclStmtNode <31:3>
          VarDeclNode <31:7> t: int
            IdExprNode <31:11> TUESDAY: enum (unnamed)
              IntConstExprNode <31:11> 2: int
        ReturnStmtNode <33:3>
          IntConstExprNode <33:10> 0: int
