ProgramNode <1:1>
  FuncDefNode <1:5> add: int (int, int)
    ParamNode <1:13> a: int
    ParamNode <1:20> b: int
    CompoundStmtNode <1:23>
      ReturnStmtNode <2:3>
        BinaryExprNode <2:12> int +
          IdExprNode <2:10> a: int
          IdExprNode <2:14> b: int
  FuncDefNode <5:5> main: int ()
    CompoundStmtNode <5:12>
      DeclVarNode <6:9> p: int (*)(int, int)
      DeclVarNode <7:7> c: int
        FuncCallExprNode <7:11> int
          IdExprNode <7:11> p: int (*)(int, int)
          ArgExprNode <7:13> int
            IntConstExprNode <7:13> 2: int
          ArgExprNode <7:16> int
            IntConstExprNode <7:16> 3: int
      ReturnStmtNode <8:3>
        IntConstExprNode <8:10> 0: int
