ProgramNode <1:1>
  FuncDefNode <1:5> add: int (int, int)
    ParamNode <1:13> a: int
    ParamNode <1:20> b: int
    CompoundStmtNode <1:23>
      ReturnStmtNode <2:3>
        BinaryExprNode <2:12> int +
          IdExprNode <2:10> a: int
          IdExprNode <2:14> b: int
  FuncDefNode <5:5> call: int (int (*)(int, int), int, int)
    ParamNode <5:16> p: int (*)(int, int)
    ParamNode <5:34> a: int
    ParamNode <5:41> b: int
    CompoundStmtNode <5:44>
      ReturnStmtNode <6:3>
        FuncCallExprNode <6:10> int
          IdExprNode <6:10> p: int (*)(int, int)
          ArgExprNode <6:12> int
            IdExprNode <6:12> a: int
          ArgExprNode <6:15> int
            IdExprNode <6:15> b: int
  FuncDefNode <9:5> main: int ()
    CompoundStmtNode <9:12>
      VarDeclNode <10:9> c: int (*)(int (*)(int, int), int, int)
        IdExprNode <10:43> call: int (int (*)(int, int), int, int)
      ExprStmtNode <11:3>
        FuncCallExprNode <11:3> int
          IdExprNode <11:3> c: int (*)(int (*)(int, int), int, int)
          ArgExprNode <11:5> int (int, int)
            IdExprNode <11:5> add: int (int, int)
          ArgExprNode <11:10> int
            IntConstExprNode <11:10> 1: int
          ArgExprNode <11:13> int
            IntConstExprNode <11:13> 2: int
      ReturnStmtNode <12:3>
        IntConstExprNode <12:10> 0: int
