ProgramNode <1:1>
  FuncDefNode <1:5> add: int (int, int)
    ParamNode <1:13> a: int
    ParamNode <1:20> b: int
    CompoundStmtNode <1:23>
      ReturnStmtNode <2:3>
        BinaryExprNode <2:12> int +
          IdExprNode <2:10> a: int
          IdExprNode <2:14> b: int
  FuncDefNode <5:5> main: int ()
    CompoundStmtNode <5:12>
      DeclVarNode <6:9> p: int (*)(int, int)
      ReturnStmtNode <7:3>
        IntConstExprNode <7:10> 0: int
