ProgramNode
  FuncDefNode main: int
    CompoundStmtNode
      DeclNode i: int
        IntConstExprNode 0: int
      IdLabeledStmtNode begin
        ExprStmtNode
          SimpleAssignmentExprNode int
            IdExprNode i: int
            BinaryExprNode int +
              IdExprNode i: int
              IntConstExprNode 1: int
      GotoStmtNode begin
      ReturnStmtNode
        IntConstExprNode 0: int
