ProgramNode <1:1>
  FuncDefNode <1:5> main: int ()
    CompoundStmtNode <1:12>
      VarDeclNode <2:7> i: int
        IntConstExprNode <2:11> 0: int
      CompoundStmtNode <3:3>
        IdLabeledStmtNode <4:3> begin
          ExprStmtNode <5:5>
            SimpleAssignmentExprNode <5:7> int
              IdExprNode <5:5> i: int
              BinaryExprNode <5:11> int +
                IdExprNode <5:9> i: int
                IntConstExprNode <5:13> 1: int
      GotoStmtNode <9:3> begin
      VarDeclNode <11:7> begin: int
      ReturnStmtNode <12:3>
        IntConstExprNode <12:10> 0: int
