ProgramNode <1:1>
  ExternDeclNode <1:1>
    FuncDefNode <1:5> main: int ()
      CompoundStmtNode <1:12>
        DeclStmtNode <2:3>
          VarDeclNode <2:7> i: int
            IntConstExprNode <2:11> 5: int
        IfStmtNode <3:3>
          BinaryExprNode <3:9> int <
            IdExprNode <3:7> i: int
            IntConstExprNode <3:11> 10: int
          // Then
          IfStmtNode <4:5>
            BinaryExprNode <4:11> int <
              IdExprNode <4:9> i: int
              IntConstExprNode <4:13> 5: int
            // Then
            ExprStmtNode <5:7>
              SimpleAssignmentExprNode <5:9> int
                IdExprNode <5:7> i: int
                IntConstExprNode <5:11> 2: int
            // Else
            ExprStmtNode <7:7>
              SimpleAssignmentExprNode <7:9> int
                IdExprNode <7:7> i: int
                IntConstExprNode <7:11> 7: int
          // Else
          ExprStmtNode <9:5>
            SimpleAssignmentExprNode <9:7> int
              IdExprNode <9:5> i: int
              IntConstExprNode <9:9> 15: int
        ReturnStmtNode <11:3>
          IdExprNode <11:10> i: int
