ProgramNode
  FuncDefNode main: int
    CompoundStmtNode
      DeclNode i: int
        IntConstExprNode 2: int
      IfStmtNode
        BinaryExprNode int <
          IdExprNode i: int
          IntConstExprNode 0: int
        // Then
        CompoundStmtNode
          ExprStmtNode
            SimpleAssignmentExprNode int
              IdExprNode i: int
              IntConstExprNode 0: int
        // Else
        CompoundStmtNode
          ExprStmtNode
            SimpleAssignmentExprNode int
              IdExprNode i: int
              BinaryExprNode int +
                IdExprNode i: int
                IntConstExprNode 1: int
      ReturnStmtNode
        IdExprNode i: int
