ProgramNode
  FuncDefNode main: int
    CompoundStmtNode
      DeclNode i: int
        IntConstExprNode 5: int
      IfStmtNode
        BinaryExprNode int <
          IdExprNode i: int
          IntConstExprNode 10: int
        // Then
        IfStmtNode
          BinaryExprNode int <
            IdExprNode i: int
            IntConstExprNode 5: int
          // Then
          ExprStmtNode
            SimpleAssignmentExprNode int
              IdExprNode i: int
              IntConstExprNode 2: int
          // Else
          ExprStmtNode
            SimpleAssignmentExprNode int
              IdExprNode i: int
              IntConstExprNode 7: int
        // Else
        ExprStmtNode
          SimpleAssignmentExprNode int
            IdExprNode i: int
            IntConstExprNode 15: int
      ReturnStmtNode
        IdExprNode i: int
