TransUnitNode <1:1>
  ExternDeclNode <1:1>
    FuncDefNode <1:5> main: int ()
      CompoundStmtNode <1:12>
        DeclStmtNode <2:3>
          VarDeclNode <2:7> i: int
            IntConstExprNode <2:11> 2: int
        IfStmtNode <3:3>
          BinaryExprNode <3:9> int <
            IdExprNode <3:7> i: int
            IntConstExprNode <3:11> 0: int
          // Then
          CompoundStmtNode <3:14>
            ExprStmtNode <4:5>
              SimpleAssignmentExprNode <4:7> int
                IdExprNode <4:5> i: int
                IntConstExprNode <4:9> 0: int
          // Else
          CompoundStmtNode <5:10>
            ExprStmtNode <6:5>
              SimpleAssignmentExprNode <6:7> int
                IdExprNode <6:5> i: int
                BinaryExprNode <6:11> int +
                  IdExprNode <6:9> i: int
                  IntConstExprNode <6:13> 1: int
        ReturnStmtNode <9:3>
          IdExprNode <9:10> i: int
