ProgramNode
  FuncDefNode main: int
    CompoundStmtNode
      DeclNode i: int
        IntConstExprNode 2: int
      IfStmtNode
        BinaryExprNode int >
          IdExprNode i: int
          IntConstExprNode 0: int
        // Then
        ExprStmtNode
          SimpleAssignmentExprNode int
            i: int
            BinaryExprNode int +
              IdExprNode i: int
              IntConstExprNode 1: int
      ReturnStmtNode
        IntConstExprNode 0: int
