ProgramNode <1:1>
  FuncDefNode <1:5> main: int
    CompoundStmtNode <1:12>
      DeclNode <2:7> i: int
        IntConstExprNode <2:11> 2: int
      IfStmtNode <3:3>
        BinaryExprNode <3:9> int >
          IdExprNode <3:7> i: int
          IntConstExprNode <3:11> 0: int
        // Then
        ExprStmtNode <4:5>
          SimpleAssignmentExprNode <4:7> int
            IdExprNode <4:5> i: int
            BinaryExprNode <4:11> int +
              IdExprNode <4:9> i: int
              IntConstExprNode <4:13> 1: int
      ReturnStmtNode <6:3>
        IntConstExprNode <6:10> 0: int
