TransUnitNode <1:1>
  ExternDeclNode <1:1>
    FuncDefNode <1:5> main: int ()
      CompoundStmtNode <1:12>
        ExprStmtNode <2:3>
          BinaryExprNode <2:5> int *
            IntConstExprNode <2:3> 4: int
            BinaryExprNode <2:10> int -
              IntConstExprNode <2:8> 5: int
              IntConstExprNode <2:12> 2: int
        ExprStmtNode <3:3>
          BinaryExprNode <3:6> int /
            IntConstExprNode <3:3> 10: int
            BinaryExprNode <3:17> int *
              BinaryExprNode <3:12> int +
                IntConstExprNode <3:10> 5: int
                IntConstExprNode <3:14> 1: int
              IntConstExprNode <3:19> 3: int
        ReturnStmtNode <5:3>
          IntConstExprNode <5:10> 0: int
