ProgramNode <1:1>
  FuncDefNode <1:5> add: int (int*, int*)
    ParamNode <1:14> x: int*
    ParamNode <1:22> y: int*
    CompoundStmtNode <1:25>
      ReturnStmtNode <2:3>
        BinaryExprNode <2:13> int +
          UnaryExprNode <2:10> int *
            IdExprNode <2:11> x: int*
          UnaryExprNode <2:15> int *
            IdExprNode <2:16> y: int*
  FuncDefNode <5:5> main: int ()
    CompoundStmtNode <5:12>
      DeclVarNode <6:7> a: int
        IntConstExprNode <6:11> 3: int
      DeclVarNode <7:7> b: int
        IntConstExprNode <7:11> 5: int
      DeclVarNode <8:8> c: int*
        UnaryExprNode <8:12> int* &
          IdExprNode <8:13> b: int
      ReturnStmtNode <9:3>
        FuncCallExprNode <9:10> int (int*, int*)
          IdExprNode <9:10> add: int (int*, int*)
          ArgExprNode <9:14> int*
            UnaryExprNode <9:14> int* &
              IdExprNode <9:15> a: int
          ArgExprNode <9:18> int*
            IdExprNode <9:18> c: int*
