ProgramNode <1:1>
  FuncDefNode <1:5> main: int
    CompoundStmtNode <1:12>
      DeclNode <2:7> a: int
        IntConstExprNode <2:11> 10: int
      DeclNode <3:8> b: int*
      DeclNode <4:8> c: int*
        UnaryExprNode <4:12> int* &
          IdExprNode <4:13> a: int
      ExprStmtNode <5:3>
        SimpleAssignmentExprNode <5:5> int*
          IdExprNode <5:3> b: int*
          IdExprNode <5:7> c: int*
      ExprStmtNode <6:3>
        SimpleAssignmentExprNode <6:6> int
          UnaryExprNode <6:3> int *
            IdExprNode <6:4> c: int*
          IntConstExprNode <6:8> 5: int
      ReturnStmtNode <8:3>
        UnaryExprNode <8:10> int *
          IdExprNode <8:11> c: int*
