ProgramNode
  FuncDefNode main: int
    CompoundStmtNode
      DeclNode a: int
        IntConstExprNode 10: int
      DeclNode b: int*
      DeclNode c: int*
        UnaryExprNode int* &
          IdExprNode a: int
      ExprStmtNode
        SimpleAssignmentExprNode int*
          IdExprNode b: int*
          IdExprNode c: int*
      ExprStmtNode
        SimpleAssignmentExprNode int
          UnaryExprNode int *
            IdExprNode c: int*
          IntConstExprNode 5: int
      ReturnStmtNode
        UnaryExprNode int *
          IdExprNode c: int*
