TransUnitNode <1:1>
  ExternDeclNode <1:1>
    FuncDefNode <1:5> main: int ()
      CompoundStmtNode <1:12>
        DeclStmtNode <2:3>
          RecordDeclNode <2:10> struct ss definition
        DeclStmtNode <4:3>
          RecordDeclNode <4:10> struct birth definition
            FieldNode <5:9> date: int
            FieldNode <6:9> month: int
            FieldNode <7:9> year: int
        DeclStmtNode <10:3>
          RecordDeclNode <10:9> struct definition
            FieldNode <11:9> quarter: int
            FieldNode <12:9> dime: int
            FieldNode <13:9> penny: int
        DeclStmtNode <16:3>
          RecordVarDeclNode <16:16> bd1: struct birth
            InitExprNode <17:5> int
              IdDesNode <17:6> date
              IntConstExprNode <17:13> 1: int
            InitExprNode <17:5> int
              IdDesNode <18:6> month
              IntConstExprNode <18:14> 1: int
            InitExprNode <17:5> int
              IdDesNode <19:6> year
              IntConstExprNode <19:13> 1995: int
        DeclStmtNode <22:3>
          RecordVarDeclNode <22:16> bd2: struct birth
            InitExprNode <22:23> int
              IntConstExprNode <22:23> 3: int
            InitExprNode <22:23> int
              IntConstExprNode <22:26> 3: int
            InitExprNode <22:23> int
              IntConstExprNode <22:29> 1998: int
        DeclStmtNode <24:3>
          ArrDeclNode <24:16> bd3: struct birth[3]
            InitExprNode <24:26> int
              ArrDesNode <24:27>
                IntConstExprNode <24:27> 0: int
              IdDesNode <24:30> date
              IntConstExprNode <24:37> 4: int
            InitExprNode <24:26> int
              ArrDesNode <24:41>
                IntConstExprNode <24:41> 1: int
              IdDesNode <24:44> year
              IntConstExprNode <24:51> 1999: int
        DeclStmtNode <26:3>
          VarDeclNode <26:16> a: struct birth
          VarDeclNode <26:20> b: struct birth*
          ArrDeclNode <26:23> c: struct birth[3]
        ExprStmtNode <28:3>
          RecordMemExprNode <28:3> .date: int
            IdExprNode <28:3> bd1: struct birth
        DeclStmtNode <30:3>
          RecordDeclNode <30:10> struct animal definition
            FieldNode <31:9> lion: int
            FieldNode <32:9> tiger: int
            FieldNode <33:9> giraffe: int
          VarDeclNode <34:5> zoo: struct animal
        DeclStmtNode <36:3>
          RecordDeclNode <36:10> struct book definition
            FieldNode <37:9> fiction: int
            FieldNode <38:9> sci_fi: int
            FieldNode <39:9> history: int
          RecordVarDeclNode <40:5> library: struct book
            InitExprNode <41:5> int
              IdDesNode <41:6> fiction
              IntConstExprNode <41:16> 100: int
            InitExprNode <41:5> int
              IdDesNode <42:6> sci_fi
              IntConstExprNode <42:15> 50: int
            InitExprNode <41:5> int
              IdDesNode <43:6> history
              IntConstExprNode <43:16> 500: int
        ReturnStmtNode <46:3>
          IntConstExprNode <46:10> 0: int
