ProgramNode <1:1>
  FuncDefNode <1:5> main: int ()
    CompoundStmtNode <1:12>
      RecordDeclNode <2:10> struct ss definition
      RecordDeclNode <4:10> struct birth definition
        FieldNode <5:9> date: int
        FieldNode <6:9> month: int
        FieldNode <7:9> year: int
      RecordDeclNode <10:9> struct definition
        FieldNode <11:9> quarter: int
        FieldNode <12:9> dime: int
        FieldNode <13:9> penny: int
      ReturnStmtNode <16:3>
        IntConstExprNode <16:10> 0: int
