TransUnitNode <1:1>
  ExternDeclNode <1:1>
    FuncDefNode <1:5> main: int ()
      CompoundStmtNode <1:12>
        DeclStmtNode <2:3>
          RecordDeclNode <2:9> union u definition
        DeclStmtNode <4:3>
          RecordDeclNode <4:9> union shape definition
            FieldNode <5:9> square: int
            FieldNode <6:9> circle: int
            FieldNode <7:9> triangle: int
        DeclStmtNode <10:3>
          RecordDeclNode <10:8> union definition
            FieldNode <11:9> a: int
            FieldNode <12:9> b: int
            FieldNode <13:9> c: int
            FieldNode <14:9> d: int
            FieldNode <15:9> e: int
        DeclStmtNode <20:3>
          RecordVarDeclNode <20:15> s: union shape
            InitExprNode <20:20> int
              IntConstExprNode <20:20> 3: int
            InitExprNode <20:20> int
              IntConstExprNode <20:23> 4: int
            InitExprNode <20:20> int
              IntConstExprNode <20:26> 5: int
        DeclStmtNode <22:3>
          RecordVarDeclNode <22:15> circle: union shape
            InitExprNode <22:25> int
              IdDesNode <22:26> circle
              IntConstExprNode <22:35> 1: int
        DeclStmtNode <23:3>
          ArrDeclNode <23:15> puzzles: union shape[3]
            InitExprNode <23:29> int
              ArrDesNode <23:30>
                IntConstExprNode <23:30> 0: int
              IdDesNode <23:33> circle
              IntConstExprNode <23:42> 1: int
            InitExprNode <23:29> int
              ArrDesNode <23:46>
                IntConstExprNode <23:46> 1: int
              IdDesNode <23:49> triangle
              IntConstExprNode <23:60> 2: int
            InitExprNode <23:29> int
              ArrDesNode <23:64>
                IntConstExprNode <23:64> 2: int
              IdDesNode <23:67> square
              IntConstExprNode <23:76> 4: int
        DeclStmtNode <25:3>
          VarDeclNode <25:15> a: union shape
          VarDeclNode <25:19> b: union shape*
          ArrDeclNode <25:22> c: union shape[3]
        ExprStmtNode <27:3>
          RecordMemExprNode <27:3> .circle: int
            IdExprNode <27:3> s: union shape
        DeclStmtNode <29:3>
          RecordDeclNode <29:9> union gender definition
            FieldNode <30:9> male: int
            FieldNode <31:9> female: int
          RecordVarDeclNode <32:5> girl: union gender
            InitExprNode <33:5> int
              IdDesNode <33:6> female
              IntConstExprNode <33:15> 1: int
        DeclStmtNode <36:3>
          RecordDeclNode <36:9> union birth_place definition
            FieldNode <37:9> tw: int
            FieldNode <38:9> us: int
          RecordVarDeclNode <39:5> yt: union birth_place
            InitExprNode <40:5> int
              IdDesNode <40:6> tw
              IntConstExprNode <40:11> 1: int
        ReturnStmtNode <43:3>
          IntConstExprNode <43:10> 0: int
