ProgramNode <1:1>
  FuncDefNode <1:5> main: int ()
    CompoundStmtNode <1:12>
      RecordDeclNode <2:9> union u definition
      RecordDeclNode <4:9> union shape definition
        FieldNode <5:9> square: int
        FieldNode <6:9> circle: int
        FieldNode <7:9> triangle: int
      RecordDeclNode <10:8> union definition
        FieldNode <11:9> a: int
        FieldNode <12:9> b: int
        FieldNode <13:9> c: int
        FieldNode <14:9> d: int
        FieldNode <15:9> e: int
      RecordVarDeclNode <20:15> s: union
        InitExprNode <20:20>
          IntConstExprNode <20:20> 3: int
        InitExprNode <20:20>
          IntConstExprNode <20:23> 4: int
        InitExprNode <20:20>
          IntConstExprNode <20:26> 5: int
      RecordVarDeclNode <22:15> circle: union
        InitExprNode <22:25>
          IdDesNode <22:26> circle
          IntConstExprNode <22:35> 1: int
      ArrDeclNode <23:15> puzzles: union[3]
        InitExprNode <23:30>
          ArrDesNode <23:31>
            IntConstExprNode <23:31> 0: int
          IdDesNode <23:34> circle
          IntConstExprNode <23:43> 1: int
        InitExprNode <23:30>
          ArrDesNode <23:47>
            IntConstExprNode <23:47> 1: int
          IdDesNode <23:50> triangle
          IntConstExprNode <23:61> 2: int
        InitExprNode <23:30>
          ArrDesNode <23:65>
            IntConstExprNode <23:65> 2: int
          IdDesNode <23:68> square
          IntConstExprNode <23:77> 4: int
      ReturnStmtNode <25:3>
        IntConstExprNode <25:10> 0: int
