ProgramNode <1:1>
  FuncDefNode <1:5> main: int ()
    CompoundStmtNode <1:12>
      VarDeclNode <2:7> i: int
        IntConstExprNode <2:11> 5: int
      WhileStmtNode <3:3>
        // While
        BinaryExprNode <3:12> int >
          IdExprNode <3:10> i: int
          IntConstExprNode <3:14> 0: int
        // Body
        CompoundStmtNode <3:17>
          ExprStmtNode <4:5>
            SimpleAssignmentExprNode <4:7> int
              IdExprNode <4:5> i: int
              BinaryExprNode <4:11> int -
                IdExprNode <4:9> i: int
                IntConstExprNode <4:13> 1: int
      ReturnStmtNode <7:3>
        IntConstExprNode <7:10> 0: int
