name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: coding convention
        run: |
          sudo apt-get install -q -y clang-format
          scripts/check-format.sh
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install QBE
        run: scripts/install-qbe.sh
      - name: Install cxxopts
        run: scripts/install-cxxopts.sh
      - name: Install Turnt
        run: pip install turnt
      - name: Run tests
        run: make test
