name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: coding convention
        run: |
          sudo apt-get install -q -y clang-format
          scripts/check-format.sh

  tidy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all history for proper diffing.
          fetch-depth: 0
      - name: Install cxxopts
        run: scripts/install-cxxopts.sh
      - name: Install fmt
        run: scripts/install-fmt.sh
      - name: Install bear
        run: sudo apt-get install -q -y bear
      - name: Install clang-tidy
        run: |
          sudo add-apt-repository -y 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main'
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -q -y clang-tidy-18
      - name: static checks
        run: |
          export CLANG_TIDY=clang-tidy-18
          make tidy

  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cxx: [g++, clang++]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install QBE
        run: scripts/install-qbe.sh
      - name: Install cxxopts
        run: scripts/install-cxxopts.sh
      - name: Install fmt
        run: scripts/install-fmt.sh
      - name: Install Turnt
        run: pip install turnt
      - name: Run tests
        run: make test CXX=${{ matrix.cxx }}
