name: CI

on: [push, pull_request]

jobs:
  lint:
    if: github.ref == 'refs/heads/main' || github.base_ref == 'main'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: coding convention
        run: |
          sudo apt-get install -q -y clang-format
          scripts/check-format.sh
